### ISSUE TITLE
About the  spectral transform?

### ISSUE THREAD

**Issue by JXH-SHU** [saic-mdal/lama#182]
Excellent work! Recently, I attempt to use your method on other tasks. After I read the code, I find that you also use the LFU in the spectral transform which is slightly different from the architecture in your paper. I'm not sure, and I may have misunderstood the code. Looking forward for your reply. 

Best wishes.

**Comment by cohimame** [comment]
Hello! Thank you!

Although we have it in `saicinpainting/training/modules/ffc.py`:
```
class SpectralTransform(nn.Module):
    def __init__(self,..., enable_lfu=True, ...):
        ...
        self.enable_lfu = enable_lfu
        ...
        if self.enable_lfu:
            self.lfu = FourierUnit(...)
```
It's not enabled in all our lama-fourier models:
` configs/training/big-lama.yaml`, `configs/training/generator/ffc_resnet_075.yaml` (it's lama-fourier):

```
...
generator:
  kind: ffc_resnet
  ...
  init_conv_kwargs:
    enable_lfu: false
    
  downsample_conv_kwargs:
    enable_lfu: false
    
  resnet_conv_kwargs:
    enable_lfu: false
```
